name       : cppcheck
version    : '1.90'
release    : 9
source     :
    - https://github.com/danmar/cppcheck/archive/1.90.tar.gz : c4864d3e09359214efdd503b52e241f4f56ba7ce26f8c11939fd9dcfac1fd105
license    : GPL-3.0-or-later
component  : programming.tools
summary    : Static source code analysis tool for C and C++ code
description: |
    Cppcheck is a static analysis tool for C/C++ code. It provides unique code analysis to detect bugs and focuses on detecting undefined behaviour and dangerous coding constructs. The goal is to detect only real errors in the code (i.e. have very few false positives).
setup      : |
    %cmake_ninja . -DBUILD_TESTS=ON -DHAVE_RULES=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
