name       : cppcheck
version    : 1.82
release    : 2
source     :
    - https://pilotfiber.dl.sourceforge.net/project/cppcheck/cppcheck/1.82/cppcheck-1.82.tar.bz2 : e02b29d18eaa38bed19e80dcf59b06d450d5e20c30732d6bad64af9ea58d694e
license    : GPL-3.0
component  : programming.tools
summary    : Static source code analysis tool for C and C++ code
description: |
    Cppcheck is a static analysis tool for C/C++ code. It provides unique code analysis to detect bugs and focuses on detecting undefined behaviour and dangerous coding constructs. The goal is to detect only real errors in the code (i.e. have very few false positives). 
setup      : |
    %cmake . -DBUILD_TESTS=ON -DHAVE_RULES=ON
build      : |
    %make
install    : |
    %make_install
check      : |
    ./bin/testrunner -q
