name       : cppcheck
version    : 1.84
release    : 4
source     :
    - https://netcologne.dl.sourceforge.net/project/cppcheck/cppcheck/1.84/cppcheck-1.84.tar.bz2 : 850beb591bb760b9a236ee481e9f6db4e0fed187ec176545de97fd3e1590e8e6
license    : GPL-3.0-or-later
component  : programming.tools
summary    : Static source code analysis tool for C and C++ code
description: |
    Cppcheck is a static analysis tool for C/C++ code. It provides unique code analysis to detect bugs and focuses on detecting undefined behaviour and dangerous coding constructs. The goal is to detect only real errors in the code (i.e. have very few false positives).
setup      : |
    %cmake . -DBUILD_TESTS=ON -DHAVE_RULES=ON
build      : |
    %make
install    : |
    %make_install
check      : |
    ./bin/testrunner -q
