name       : cppcheck
version    : 1.83
release    : 3
source     :
    - https://netcologne.dl.sourceforge.net/project/cppcheck/cppcheck/1.83/cppcheck-1.83.tar.bz2 : 03b515432a2604ffb84aa18ff7d86916e73c74fe9b6f9ff1e5504bf0a553a491
license    : GPL-3.0-or-later
component  : programming.tools
summary    : Static source code analysis tool for C and C++ code
description: |
    Cppcheck is a static analysis tool for C/C++ code. It provides unique code analysis to detect bugs and focuses on detecting undefined behaviour and dangerous coding constructs. The goal is to detect only real errors in the code (i.e. have very few false positives).
setup      : |
    %cmake . -DBUILD_TESTS=ON -DHAVE_RULES=ON
build      : |
    %make
install    : |
    %make_install
check      : |
    ./bin/testrunner -q
