name       : cppcheck
version    : '2.7'
release    : 17
source     :
    - https://github.com/danmar/cppcheck/archive/2.7.tar.gz : 5fd20549bb2fabf9a8026f772779d8cc6a5782c8f17500408529f7747afbc526
license    : GPL-3.0-or-later
component  : programming.tools
summary    : Static source code analysis tool for C and C++ code
description: |
    Cppcheck is a static analysis tool for C/C++ code. It provides unique code analysis to detect bugs and focuses on detecting undefined behaviour and dangerous coding constructs. The goal is to detect only real errors in the code (i.e. have very few false positives).
builddeps  :
    - pkgconfig(z3)
setup      : |
    %cmake_ninja . -DBUILD_TESTS=ON -DHAVE_RULES=ON -DUSE_MATCHCOMPILER=ON -DUSE_Z3=yes
build      : |
    %ninja_build
install    : |
    %ninja_install
