name       : cppcheck
version    : 2.6.1
release    : 16
source     :
    - https://github.com/danmar/cppcheck/archive/2.6.1.tar.gz : 41700db44b349428d5602356b32183b7776380e7a5b0b82a2f2764fadadb015e
license    : GPL-3.0-or-later
component  : programming.tools
summary    : Static source code analysis tool for C and C++ code
description: |
    Cppcheck is a static analysis tool for C/C++ code. It provides unique code analysis to detect bugs and focuses on detecting undefined behaviour and dangerous coding constructs. The goal is to detect only real errors in the code (i.e. have very few false positives).
builddeps  :
    - pkgconfig(z3)
setup      : |
    %cmake_ninja . -DBUILD_TESTS=ON -DHAVE_RULES=ON -DUSE_MATCHCOMPILER=ON -DUSE_Z3=yes
build      : |
    %ninja_build
install    : |
    %ninja_install
