name       : cppcheck
version    : 1.76.1
release    : 1
source     :
    - https://pilotfiber.dl.sourceforge.net/project/cppcheck/cppcheck/1.76.1/cppcheck-1.76.1.tar.bz2 : 5bc70fdc59e242ee882ec9c98738b43e7b46919c78015a6acaceeb527f5d86d0
license    : GPL-3.0
component  : programming.tools
summary    : Static source code analysis tool for C and C++ code
description: |
    Static source code analysis tool for C and C++ code
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
