name       : cppcheck
version    : 2.9.1
release    : 20
source     :
    - https://github.com/danmar/cppcheck/archive/2.9.1.tar.gz : c166b86aebe80faa08c80196c9156b73e9ffaf8eccd84f9317c51f62577028df
license    : GPL-3.0-or-later
component  : programming.tools
summary    : Static source code analysis tool for C and C++ code
description: |
    Cppcheck is a static analysis tool for C/C++ code. It provides unique code analysis to detect bugs and focuses on detecting undefined behaviour and dangerous coding constructs. The goal is to detect only real errors in the code (i.e. have very few false positives).
setup      : |
    %cmake_ninja . -DBUILD_TESTS=ON -DHAVE_RULES=ON -DUSE_MATCHCOMPILER=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
